before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: XVjvH/ZloRdoREdjkjllM3PItOLYjqCYONEV/T88DX2AwIG8qHX69yQqqYHu/6stSHVUcMHkhb2N9+fP4wX1MDoov1/O809sysCZZVQPfpcVLqTMroK+HlSxYCJIsJYBEJPEntwF91e0EVnIVLjXp8mpBwQzBNnNS7rg/pNSCfLBlm1ZQ6cB3qFb45IpSqD6SMLP7xM7mZ/jcT4cIOSwbFqExSAdRTLUkmPx3C5o9Y0W4UsD9vVARRePePYDfrBMJvlwwaj5lZvLKL0WOMZBliueY2mSyPMo3NeHPgzhz0E3lv4AaYbm3WuvWgyD7zo8005bNPTJm/oOxkIJX8xMJvMLWVxHcGIlxQCdKHcKGvNR/yBy2REAKT00AjGHheA7vt5Jwt0WM8I2pJQV6rS5uix5FmY4PT9xdFnOTYT/7cpv7Ini9m+C2FMYZIZItfKdM5ZTOQMIoxNLu2czKBV3BGTktnmHYek7JBuPCO+jXY/F8L5EnXQ1+6KMZmcKtFN9Zs53yMXC5bhU2yPwg0VxbGHthGM/jUkhikuabel61jDi0j616Bc1OTxtSTQxuOJ43/erdkw/EYNX7W1+VHFx8ekRtzP6ViMnqCaxPqeZL64nhys5HgtnOvBIdYsY95LxYnvAk6O62v8IS76q7pugekUKiYaCYSRQF14Na2F8M2U= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
